# Generated by Django 5.0.4 on 2024-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_discount_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.CharField(default='Unknown Publication', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='writer',
            field=models.CharField(default='Unknown Writer', max_length=100),
        ),
    ]
