# Generated by Django 5.0.4 on 2024-08-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
